i18n/ru.json

ManageWiki Russian translation

Add Russian translation

---

i18n/es.json

I have translated the ManageWiki extension from Miraheze into Spanish. I request that it be merged into the source code of the extension. Thanks.

Spanish Translation for ManageWiki Extension

---

i18n/es.json

Arrangement in Spanish articles ("un" → "una", "el" → "la") and others translation arrangements. Thanks.

Fix Spanish Articles (Grammar) and Others Translations Arrangements

---

includes/SpecialManageWikiPermissions.php

$wgManageWikiPermissionsBlacklistRights can now set a blacklist for individual groups. Use key any to blacklist for any group.

Upgrade $wgManageWikiPermissionsBlacklistRights

---

includes/ManageWikiCDB.php

Reverts miraheze/ManageWiki#54
Also breaks it anyway as not using correct variable

Revert "Fix wgNamespacesToBeSearchedDefault when nsID === 0"

---

includes/formFactory/ManageWikiFormFactory.php

it doesn't work as is, and looks like it's trying to do the same thing as the way that actually works

fix disabled logic for conflicting exts

---

includes/ManageWikiHooks.php

fix allowing sysops to add it, and make it so that it is completely removed

updates to default private group handling

---

maintenance/populateGroupPermissionsWithDefaults.php

This script will allow us to quickly add default perms to wiki that are missing it.

Add populateGroupPermissionsWithDefaults script

---

includes/formFactory/ManageWikiFormFactoryBuilder.php

fix blacklist dropping rights

---

includes/ManageWikiHooks.php

Reverts miraheze/ManageWiki#87

Revert "apply sql patch through update.php"

---

i18n/en.json
i18n/qqq.json
includes/api/ApiQueryWikiConfig.php

Also adds missing i18n "apihelp-query+wikiconfig-summary"

api: Add an example to get the api

---

maintenance/populateNamespacesWithDefaults.php

This is aka to resetting all namespaces back to default for a the wiki.

Add a script to add default namespaces

---

includes/helpers/ManageWikiDeletedWikiPager.php

go to Special:ManageWiki/core/dbname instead of Special:ManageWiki/dbname

fix managewiki link in DeletedWikis

---

includes/formFactory/ManageWikiFormFactory.php
includes/specials/SpecialManageWiki.php
includes/specials/SpecialManageWikiDefaultPermissions.php

Sometimes $formFactory->getForm can return a bool, so handle it correctly.

Fix "Call to a member function getFormSections() on bool"

---

includes/specials/SpecialManageWiki.php

Force group name to be lowercased

---

includes/ManageWikiHooks.php

modifyTable  -> modifyExtensionTable

---

includes/helpers/ManageWikiPermissions.php

Reverts miraheze/ManageWiki#163

Revert "Add null check"

---

includes/helpers/ManageWikiExtensions.php

If the extension is not in liveExts, don't continue.

Fix undefined index in remove

---

includes/formFactory/ManageWikiFormFactoryBuilder.php

Use ->list( $id ) over ->list() for permission settings in formBuilder

---

includes/formFactory/ManageWikiFormFactoryBuilder.php

This merges options with userrights if defined.

support 'options' under 'userrights'

---

includes/formFactory/ManageWikiFormFactoryBuilder.php

Update dblist after deleting/undeleting a wiki

---

includes/formFactory/ManageWikiFormFactoryBuilder.php

To be used for miraheze/mw-config#3412.
#200 should be merged first as it would be easier to resolve the merge conflicts that would arise either way.

Support 'from' in ManageWikiNamespacesAdditional

---

includes/formFactory/ManageWikiFormFactoryBuilder.php

use ksort for skin/skins type

---

includes/formFactory/ManageWikiFormFactoryBuilder.php
includes/specials/SpecialManageWiki.php

Reverts miraheze/ManageWiki#226

Revert "autofill namespace names when creating new namespace"

---

includes/helpers/ManageWikiInstaller.php
includes/helpers/ManageWikiNamespaces.php

Reverts miraheze/ManageWiki#242

Revert "fix"

---

includes/helpers/ManageWikiInstaller.php
includes/helpers/ManageWikiNamespaces.php

Reverts miraheze/ManageWiki#243
Thought this was not needed, but it was.

Revert "Revert "fix""

---

includes/helpers/ManageWikiInstaller.php
includes/helpers/ManageWikiNamespaces.php

Reverts miraheze/ManageWiki#247

Revert "fix restoring namespace when re-enabling"

---

extension.json

Temporarily remove api

---

extension.json

Reverts miraheze/ManageWiki#269

Revert "Temporarily remove api"

---

extension.json
includes/formFactory/ManageWikiFormFactory.php
includes/helpers/ManageWikiExtensions.php
includes/helpers/ManageWikiInstaller.php
includes/helpers/ManageWikiNamespaces.php
includes/helpers/ManageWikiPermissions.php
includes/helpers/ManageWikiSettings.php
includes/jobs/NamespaceMigrationJob.php
includes/specials/SpecialManageWikiDefaultPermissions.php
maintenance/migrateSettingsAndExtensions.php
maintenance/populateGroupPermissions.php
maintenance/populateGroupPermissionsWithDefaults.php
maintenance/populateNamespaces.php
maintenance/populateNamespacesWithDefaults.php

DB_MASTER is renamed to DB_PRIMARY on 1.36

DB_MASTER -> DB_PRIMARY

---

includes/formFactory/ManageWikiFormFactoryBuilder.php

Per [T7125](https://phabricator.miraheze.org/T7125)
miraheze/mw-config#3990 sets up ManageWikiExtensions.php to support this.

ManageWikiExtensions: support description and name messages

---

.eslintrc.json
.github/workflows/continuousIntegration.yml
.gitignore
.phan/config.php
.phpcs.xml
includes/ManageWiki.php
includes/formFactory/ManageWikiFormFactoryBuilder.php
includes/helpers/ManageWikiPermissions.php
includes/helpers/ManageWikiRequirements.php
includes/helpers/ManageWikiTypes.php
includes/jobs/MWScriptJob.php
includes/jobs/NamespaceMigrationJob.php
includes/specials/SpecialManageWiki.php
includes/specials/SpecialManageWikiDefaultPermissions.php
maintenance/addNamespaces.php
maintenance/migrateSettingsAndExtensions.php
maintenance/modifyGroupPermission.php
maintenance/populateGroupPermissions.php
maintenance/populateGroupPermissionsWithDefaults.php
maintenance/populateNamespaces.php
maintenance/populateNamespacesWithDefaults.php
maintenance/populateWikiSettings.php
maintenance/toggleExtension.php
modules/ext.managewiki.oouiform.confirmClose.js
modules/ext.managewiki.oouiform.reviewChanges.js
modules/ext.managewiki.oouiform.tabs.js
phpcbf.sh

[T7942](https://phabricator.miraheze.org/T7942)
Adds eslint, stylelint, phpcs, and phan to check for mediawiki standard issues. Automatically commits fixes for some formatting issues.
I18n check available but disabled due to 78 messages missing from qqq.json, causing failures. That probably needs fixed eventually.

Add CI for MediaWiki standards and security

---

modules/ext.managewiki.oouiform.confirmClose.js

Then we can remove result variable and the code is shorter.

cleanup: Use for loop instead of each() function

---

includes/FormFactory/ManageWikiFormFactoryBuilder.php
includes/Helpers/ManageWikiTypes.php
modules/ext.managewiki.oouiform.styles.less

Adds `'texts'` type and the styles for widening the form.

Add texts type

---

includes/Specials/SpecialManageWiki.php
includes/Specials/SpecialManageWikiDefaultPermissions.php

Make addModuleStyles an array

---

includes/FormFactory/ManageWikiFormFactoryBuilder.php

Fix reverting to default if default is empty string

---

maintenance/migrateSettingsAndExtensions.php
maintenance/populateGroupPermissions.php
maintenance/populateGroupPermissionsWithDefaults.php
maintenance/populateNamespaces.php
maintenance/populateNamespacesWithDefaults.php

maintenance: replace usages of wfGetDB

---

includes/FormFactory/ManageWikiFormFactory.php

It was instead displaying in the wikis main language and not the language the user has set in their preference.

Fix displaying the error in the users language

---

includes/FormFactory/ManageWikiFormFactoryBuilder.php
includes/Hooks/ManageWikiCoreFormSubmissionHook.php
includes/Hooks/ManageWikiHookRunner.php

Also fixes passing some others

Pass $wiki to ManageWikiCoreFormSubmission

---

includes/Helpers/ManageWikiSettings.php

If setting isn't set inside the db for that wiki then continue in the foreach.

ManageWikiSettings: Add isset check inside remove

---

includes/Helpers/ManageWikiNamespaces.php
includes/Hooks.php
includes/Jobs/NamespaceMigrationJob.php

It's not needed and won't work.

Don't execute ManageWikiNameSpaceMigration job on wiki creation

---

includes/Helpers/ManageWikiPermissions.php
includes/Hooks.php

Also makes the code slightly more readable by breaking the lines.

Fix "Passing null to parameter #1 ($json)"

---

.github/workflows/mediawiki-tests.yml

Test against MW 1.41

---

modules/ext.managewiki.oouiform.tabs.js

remove outdated eslint directive

---

includes/FormFactory/ManageWikiFormFactoryBuilder.php

Seems to have been broken since wikimedia/mediawiki@9c9514a (MediaWiki 1.38)

Fix hide-if

---

maintenance/toggleExtension.php

fix logic error when using --disable

---

i18n/en.json
i18n/qqq.json
includes/Specials/SpecialManageWiki.php

RemoteWiki will automatically handle nice error for wiki not existing now

Remove use of WikiManager (T12716)

---

includes/Hooks.php

We log an error to tell us what extension failed to load due to not being in the config. More useful information then telling us a null was set on an array.

Fix "PHP Warning: Trying to access array offset on value of type null"

---

i18n/en.json
i18n/qqq.json
includes/FormFactory/ManageWikiFormFactoryBuilder.php
includes/Helpers/ManageWikiNamespaces.php
includes/Helpers/ManageWikiPermissions.php
includes/Helpers/ManageWikiSettings.php

Relevant Task: [T10230](https://issue-tracker.miraheze.org/T10230)

Disallow removing managewiki-permissions from all groups

---

i18n/en.json
includes/FormFactory/ManageWikiFormFactoryBuilder.php
includes/Helpers/ManageWikiNamespaces.php
includes/Helpers/ManageWikiTypes.php
includes/Specials/SpecialManageWiki.php

Relevant Task: [T11173](https://issue-tracker.miraheze.org/T11173)

Add namespace name validation

---

includes/FormFactory/ManageWikiFormFactoryBuilder.php

Fixes [T12200](https://issue-tracker.miraheze.org/T12200)

Fix implicit submission for namespace aliases fields

---

includes/FormFactory/ManageWikiFormFactoryBuilder.php

Relevant task: [T12055](https://issue-tracker.miraheze.org/T12055)

Add support to use display names with clusters

---

includes/Helpers/ManageWikiTypes.php

Unused and allows return type to be only an array

Remove json support from handleMatrix

---

includes/Hooks/Handlers/CreateWiki.php

To be consistent with what ExtensionsModule does

Update message for logging

---

includes/FormFactory/FormFactoryBuilder.php
includes/Helpers/ExtensionsModule.php
includes/Helpers/Factories/ExtensionsFactory.php
includes/Helpers/Factories/RequirementsFactory.php
includes/Helpers/Requirements.php
includes/Helpers/SettingsModule.php
includes/ServiceWiring.php

This adds cross-database support for all except permissions which will be done later, as the current will need rewritten to change how all permissions are checked to support that.

Make Requirements cross-database compatible

---

extension.json
modules/ext.managewiki.oouiform.styles.less
modules/ext.managewiki.oouiform.styles.minerva.less

https://discord.com/channels/407504499280707585/1006789349498699827/1389604097157496843

Fix incorrect alignments for OOUI cloner fields
