- i18n/en.json
- includes/SpecialManageWikiPermissions.php
"delete" is reserved in LogEntry for regular MediaWiki deletion logs.
> fix delete group logentry

- includes/ManageWikiHooks.php
In the future if we expect the value to be a string then we should change this but for now this fixes a issue where it's returning non array and object values.
> ManageWikiHooks: Fix it so that it will continue in the foreach if value is not a array or object

- includes/specials/SpecialManageWikiDefaultPermissions.php
* Fixes a issue where by it try's to create the log but fails with "Argument 1 passed to ManualLogEntry::setTarget() must be an instance of Title"
* Put's a new line break in the if statement to make it readable.
* Removes memcache cache support as we doin't use memcache and we doin't use the cache either.
* * We should rather support all cache types if we want caching rather then a specific cache type.
> Fix SpecialManageWikiDefaultPermissions

- includes/ManageWikiCDB.php
null == false, so all versions get set to 0, and the cache is never set properly
> fix if else execution

- includes/ManageWiki.php
groups such as interface-admin are getting truncated to interface
> prevent accidental loss of information

- maintenance/populateGroupPermissionsWithDefaults.php
This script was adding namespaces and updating cw_wikis which is not what was supposed to happen.
This fixes it by copying the bits we want that touches perms.
> Fix populateGroupPermissionsWithDefaults script

- includes/formFactory/ManageWikiFormFactoryBuilder.php
- includes/helpers/ManageWikiRequirements.php
feels like a hack, but just adding a parameter to ManageWikiRequirements::process to ignore the permissions check seems like a decent temporary solution, barring a rewrite
> only check perms on install

- i18n/en.json
Per https://phabricator.wikimedia.org/T241300
> Fix typo of Apihelp-query+wikiconfig-paramvalue-prop-permissions message in en.json

- includes/formFactory/ManageWikiFormFactoryBuilder.php
Sometimes the content model is managed by the extension it's self so no need for us to manage it.
Fixes T4699
> Support an empty content model

- includes/helpers/ManageWikiRequirements.php
This fixes an issue where 'required' extensions were being ignored.
E.g you could enable wikibaseclient even though wikibaserepository was required.
Bug: T5596
> Fix ManageWikiRequirements::extensions

- includes/formFactory/ManageWikiFormFactoryBuilder.php
Add check so that if $mwReturn returns an array,
call errors by doing '$mwReturn['errors']' and if it is an object
then call it with '$mwReturn->errors'.
```
> $test = [ 'errors' => false, ];
> var_dump($test->errors);
PHP Notice:  Trying to get property 'errors' of non-object in /srv/mediawiki/w/maintenance/eval.php(78) : eval()'d code on line 1
Notice: Trying to get property 'errors' of non-object in /srv/mediawiki/w/maintenance/eval.php(78) : eval()'d code on line 1
NULL
```
log:
```
/wiki/Speciale:ManageWiki/core   ErrorException from line 802 of /srv/mediawiki/w/extensions/ManageWiki/includes/formFactory/ManageWikiFormFactoryBuilder.php: PHP Notice: Trying to get property 'errors' of non-object
```
> Fix getting errors in submissionHandler

- includes/formFactory/ManageWikiFormFactoryBuilder.php
It was checking the wrong value, thus always was unset.
Bug: T5653
> Fix bug with isset check

- includes/ManageWikiHooks.php
Changes addgroup/removegroup value to be an array.
Example:
```
> $permData = [ 'addgroups' => [] ];
> $test = array_merge( $permData['addgroups'], 'test' );
PHP Warning:  array_merge(): Expected parameter 2 to be an array, string given in /srv/mediawiki/w/maintenance/eval.php(78) : eval()'d code on line 1
Warning: array_merge(): Expected parameter 2 to be an array, string given in /srv/mediawiki/w/maintenance/eval.php(78) : eval()'d code on line 1
> var_dump($test);
NULL
```
Bug: T5660
> Fix ::onCreateWikiStatePrivate

- includes/ManageWikiHooks.php
Fixes an issue when switching from private to public.
Bug: T5697
> Fix addgroups/removegroups becomming null in the db

- maintenance/modifyGroupPermission.php
Fixes the following issues:
* When removing a perm from a group, the script would convert it into an object rather than keeping it as an array,
e.g [] -> {}. This is now fixed.
* When the script removed the last perm, the group still existed rather than deleting it. This is now fixed.
* When explode second argument returned a empty string because the option wasn't used on the command line,
it returned a empty array so array( 0 -> '' ) (so basically object). This is now fixed.
> Fix modifyGroupPermission script

- .travis.yml
PHP7.2 is dropped in REL1_35
OS parameter should be stated, fixes a build info thing. Similar PR should probably done on all php repos.
> travis: drop php7.2 test and explicitly state os

- maintenance/populateWikiSettings.php
These should be required and also should be known as args.
This fixes it so you can do --wgsetting <setting> rather than forced to do --wgsetting=<setting>
> ManageWikiPopulateSettings: Fix args

- includes/formFactory/ManageWikiFormFactoryBuilder.php
* `float` type would be useful for configs that need it; nothing in particular
* `skins` type would be useful to improve upon the method used with `$wgDefaultSkins` to support `$wgSkipSkins` as well as prevent us from having to add `$wgManageWikiSettings['wgDefaultSkin']['options']['DISPLAYNAME'] = 'SKINNAME';` for every skin,
> Add float and skins types to ManageWiki

- includes/formFactory/ManageWikiFormFactoryBuilder.php
Because if it is null then https://github.com/miraheze/ManageWiki/blob/02bd453558b3ee687c7b2066fa364897411aca21/includes/formFactory/ManageWikiFormFactory.php#L72 would return invalid argument for foreach()
> use array on array for return on managewiki-changes-none

- includes/specials/SpecialManageWikiDefaultPermissions.php
Spotted it today while checking something.
Looks like it should just be 'create' not 'creategoup' or at least that's what Special:ManageWiki does
> DefaultPermissions: fix broken message tag

- extension.json
- includes/ManageWikiHooks.php
- includes/formFactory/ManageWikiFormFactoryBuilder.php
- includes/helpers/ManageWikiTypes.php
* Add new `contentmodel` type to use for the ManageWikiNamespaces `contentmodel` field, instead of the `$wgManageWikiNamespacesExtraContentModels` config.
* Remove `$wgManageWikiNamespacesExtraContentModels` from `extension.json`.
* Use `combobox` type instead of `selectorother`, for the ManageWikiNamespaces `protection` field, since this is cleaner.
* Add config variables to ManageWikiNamespaces labels.
* Add support to ManageWikiNamespacesAdditional, for localised labels and help messages.
* Add support for constant namespace-related configs to be added to ManageWikiNamespaces, such as configs that don't just effect one namespace, or that are not part of an array of namespaces.
* Should add support for `$wgMetaNamespace` and `$wgMetaNamespaceTalk`. `'blacklisted'` would be used to only …
> Multiple improvements to ManageWikiNamespaces

- includes/helpers/ManageWikiTypes.php
downloaduserdata is available since 1.35.2, it should never be hidden with wgHiddenPrefs, as users should always be able to see/use it.
> Blacklist downloaduserdata from preferences form type

- includes/helpers/ManageWikiTypes.php
This prevents the `foreach` `=> $value` from overwriting the set config `$value` thus not correctly displaying config as the HTMLForm field default.
> [BUG FIX] fix preferences type

- includes/formFactory/ManageWikiFormFactoryBuilder.php
Also makes it required to set a section with ManageWikiExtensions and ManageWikiSettings. Does not need to add a check, doing per T7125 and conversation with Joritochip on Discord.
> A little maintenance to make things easier to read

- extension.json
- i18n/en.json
- i18n/qqq.json
- includes/formFactory/ManageWikiFormFactory.php
- includes/helpers/ManageWikiOOUIForm.php
- includes/specials/SpecialManageWiki.php
- modules/ext.managewiki.oouiform.confirmClose.js
- modules/ext.managewiki.oouiform.js
- modules/ext.managewiki.oouiform.styles.less
Also:
* Disables the save button until changes are made.
* Lazy-infuses fields, so won't infuse until you are on the tab, to further improve performance.
* Fixes a JavaScript error on ManageWiki special pages without anything to infuse (like namespaces and permissions) - it does not allow the resources to load in that case, as it's redundant to anyways.
> Give close confirmation if settings are changed

- includes/formFactory/ManageWikiFormFactoryBuilder.php
[$wgExtensionCredits](https://www.mediawiki.org/wiki/Manual:$wgExtensionCredits) is deprecated and only used by some extensions already. In the future, It would be empty. This prepares the situation.
> Merge ExtensionCredits only if given

- includes/formFactory/ManageWikiFormFactoryBuilder.php
- includes/helpers/ManageWikiOOUIForm.php
- includes/helpers/ManageWikiTypes.php
- modules/ext.managewiki.oouiform.confirmClose.js
- modules/ext.managewiki.oouiform.styles.less
- modules/ext.managewiki.oouiform.tabs.js
This adds a new type `'integers'` using [HTMLFormFieldCloner](https://github.com/wikimedia/mediawiki/blob/REL1_37/includes/htmlform/fields/HTMLFormFieldCloner.php) class. This is inspired by [Special:GlobalWatchlistSettings](https://meta.wikimedia.org/wiki/Special:GlobalWatchlistSettings)' user defined site list.
There are several following TODOs:
Bugs:
- Pushing the 'Add more' button adds two more fields.
- The review changes dialog exposes not formatted diffs. Example:
> wgExampleIntegersConfig[1][integer] (Other) was changed from 2 to 1
>wgExampleIntegersConfig[clone1][integer] (Other) was changed from <none> to 11
- Without javascript, HTMLFormFieldCloner's buttons act as submit button, and Special:ManageWiki does not allow to leave the submit-reason field empty. Thus, the user should …
> Add a new type 'integers'

- includes/FormFactory/ManageWikiFormFactoryBuilder.php
Should support configuration like the following:
```php
'wgExample' => [
'associativeKey' => 'associativeKeyExample',
'name' => 'Example Usage of AssociativeKey',
'from' => 'mediawiki',
'global' => true,
'type' => 'text',
'overridedefault' => [
'associativeKeyExample' => 'example',
'other-unmodified-associative-key-example' => [
'example' => 'example',
],
],
'section' => 'example',
'help' => 'Example associative array configuration key.',
'requires' => [],
],
```
Which should support configuring `$wgExample['associativeKeyExample']`.
This is just doing this the simplest way to achieve this probably. It would be nicer to achieve this using the below format, but if not done yet, that can probably be done later on without requiring additional steps to deploy, such as SQL queries, etc, should …
> Support associative arrays in ManageWikiSettings

- includes/Helpers/ManageWikiTypes.php
Namespace configs are set via ManageWikiNamespaces, these types are unused.
> Remove unused namespace(s) types

- includes/FormFactory/ManageWikiFormFactoryBuilder.php
To prevent it from returning `[""]` (an array with an empty string)
> Fix users and wikipages type return

- includes/FormFactory/ManageWikiFormFactoryBuilder.php
The other day, I nearly deleted Meta as I thought I was on the /core page for another wiki. With this PR, the buttons to delete/lock the 'global wiki' are disabled so that no blunder can occur on the most important wiki.
> Prevent deletion of global wiki

- i18n/en.json
- i18n/qqq.json
- includes/Specials/SpecialDeletedWikis.php
Reverts miraheze/ManageWiki#382
This is Miraheze specific... a message like this is not needed for an override set in MirahezeMagic.
We use `SpecialPage::outputHeader()` instead, so the message can be set as `deletedwikis-summary` in MirahezeMagic, or nothing if the message does not exist. Doesn't need to be an override, just adding the message.
> Revert "add header for Special:DeletedWikis"

- i18n/en.json
If I understand correctly, it's supposed to be "added" everywhere. If I misunderstand, please discard it. Thanks.
> Correction of logentry-managewiki-rights

- i18n/en.json
This word was recently removed, and it probably happened by mistake.
> Restore "are" in managewiki-header-extensions

- includes/Helpers/ManageWikiInstaller.php
Use case is something like this:
```php
'install' => [
'mwscript' => [
"$IP/extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php" => [],
"$IP/extensions/CirrusSearch/maintenance/ForceSearchIndex.php" => [
'skipLinks' => false,
'indexOnSkip' => false,
'repeat-with' => [
'skipParse' => false,
],
],
],
],
```
> ManageWikiInstaller: support running mwscript twice with different options

- includes/Helpers/ManageWikiNamespaces.php
It was using the wiki that was creating the wiki rather then the wiki that has been created.
> Fix bug with creating MWN jobs on wiki creation

- includes/Helpers/ManageWikiNamespaces.php
- includes/Jobs/NamespaceMigrationJob.php
We cannot use the wiki we're creating for creating jobs because LocalDatabases isn't updated in time. Instead lets pass along 'wiki' to the job and open the db connection with that.
> Pass 'wiki' along to NamespaceMigrationJob

- includes/Hooks.php
The localization cache may be missing (ex due to an upgrade), failing to account for this will prevent maintenance scripts from running.
> onCreateWikiJsonBuilder: expect possibility of missing LC

- i18n/en.json
- includes/Specials/SpecialManageWikiDefaultPermissions.php
This message, named managewikidefaultpermissions-norights, was introduced in https://github.com/miraheze/ManageWiki/pull/438. i18n for it was not added though.
This PR adds that missing i18n, in the same style as the other *-view messages.
> Add missing i18n for managewikidefaultpermissions-view

- modules/ext.managewiki.oouiform.tabs.js
This fixes hide-if functionality in ManageWiki, unless trying to use hide-if in a tab where cloner is present, as using lazy infuse with cloners causes a conflict and each time a field is added to cloner it will actually add two fields.
> Only disable lazy infuse if using cloner fields

- maintenance/populateNamespaces.php
dbw->select always returns an IResultsWrapper object (now)
fixed some weird logic
> Fix populateNamespaces.php

- includes/Helpers/ManageWikiExtensions.php
- includes/Hooks.php
- maintenance/toggleExtension.php
* Logs error if ext does not exist in config.
* Allows removing ext when it does not exist in config.
Bug: T12868
> ManageWikiExtensions: Log error if ext is not set in config && allow removing

- includes/FormFactory/ManageWikiFormFactoryBuilder.php
- includes/Helpers/ManageWikiPermissions.php
While they shouldn't exist (the code automatically deletes groups if all rights are removed from them), they apparently sometimes happen anyway (otherwise, this bug wouldn't have been noticed).
Closes T12896
> T12896: Fix deleting groups with no permissions

- includes/Helpers/ManageWikiTypes.php
Matches change done in Special:ManageWiki.
> ManageWikiTypes: Lowe case group for uaergroups types

- includes/Helpers/ManageWikiTypes.php
It's always defined so we only need to check if it returns null.
> ManageWikiTypes: Remove isset check for $value

- i18n/en.json
Changed "critera" to "criteria".
> Fix typo in autopromotion message

- includes/Helpers/ManageWikiSettings.php
We were using json_encode with an empty array.
> ManageWikiSettings: Don't look for s_extensions in upsert

- includes/Helpers/ManageWikiExtensions.php
We were using json_encode with an empty array.
> ManageWikiExtensions: Don't look for s_settings in upsert

- includes/FormFactory/ManageWikiFormFactoryBuilder.php
- includes/Helpers/ManageWikiNamespaces.php
- includes/Helpers/ManageWikiPermissions.php
- includes/Specials/SpecialManageWiki.php
To solve numerous bugs with change tracking if you reload multiple times when deleting groups and namespaces.
> Add redirect when deleting groups and namespaces

- extension.json
- includes/Hooks/Handlers/Main.php
- includes/Hooks/ManageWikiAfterSidebarLinksHook.php
- includes/Hooks/ManageWikiHookRunner.php
Needed for DataDump to be able to add the sidebar link for it since the order was changed when this was moved to HookHandlers, so the hooks in ManageWiki are loaded after DataDump causing a race condition, and it not adding a link there. It could also have other benefits as well.
> Add hook to add sidebar links to managewiki-sidebar-header

- includes/Helpers/ManageWikiInstaller.php
- includes/Jobs/MWScriptJob.php
Sometimes causes Jobs like CirrusSearch to fail "index(es) do not exist. Did you forget to run updateSearchIndexConfig?" when running ForceSearchIndex in same install step when it relies on the order that needs to ensure UpdateSearchIndexConfig runs first.
> Fix race condition when running multiple scripts

- includes/Hooks/Handlers/CreateWiki.php
When we are catching an exception to log it's an error not a warning
> Use error log

- sql/mw_namespaces.sql
- sql/mw_permissions.sql
- sql/mw_settings.sql
- sql/patches/patch-autopromote.sql
- sql/patches/patch-groups-self.sql
- sql/patches/patch-namespaces-additional.sql
Technically this is just an alias to LONGTEXT but it also adds a constraint ensuring valid JSON
> Use JSON datatype for JSON fields

- maintenance/ToggleExtension.php
Avoid there being no output when nothing happens as --name is not validated against ManageWiki config anywhere
Don't show when --all-wikis passed to avoid spam
> ToggleExtension: warn when disable not possible
